name = "umi"
compatibility_date = "2023-12-01"
pages_build_output_dir = ".vercel/output/static"
functions = ".vercel/output/functions"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".vercel/output/static"

