name = "umi"
compatibility_date = "2023-12-01"

# Pages configuration
[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

# The directory with your static files
[site]
bucket = "out"

# Required for Pages deployments
pages_build_output_dir = "out" 