name = "uminda-portfolio"
compatibility_date = "2023-12-01"
account_id = "e0584d5d8d24ac7a41a567095fec197a"
main = "./out"

[build]
command = "npm run build"

[site]
bucket = "out"

[build.environment]
NODE_VERSION = "18"

pages_build_output_dir = "out"

[pages]
build_output_dir = "out" 